
training_pipeline_config:
  pipeline_name: census
  artifact_dir: artifact

data_ingestion_config:
  db_client_id: DTmBKcZuXZvMkgNkSYvUNTZA
  db_client_secret: UEeoXPUu75+QAyBRp-KXm7f8vfFkTt.pw8IyZZDJJsTF3BFHkEDqjZPD5uPuO-xT3Fpjdz4Qs6Tg1L,DrabSSGerUsU+FuORqAbgZ3qjw6xl1yESIZpY+jpmb4yLitAe
  db_token: AstraCS:DTmBKcZuXZvMkgNkSYvUNTZA:f984d1cc152f46c437e7a67fbaad9494728776bb47c566c9e3feb3156de367da
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 




data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  add_bedroom_per_room: true
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  
model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: model.yaml


model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml
  

model_pusher_config:
  model_export_dir: saved_models