columns:
  age: int
  workclass: object
  fnlwgt : int
  education: object
  education_num: int
  marital_status: object
  occupation: object
  relationship: object
  race: object
  sex: object
  capital_loss : int
  capital_gain : int
  hours_per_week: int
  country: object
  salary: object

numerical_columns:
  - age 
  - education_num
  - hours_per_week

categorical_columns:
  - workclass
  - education
  - marital_status
  - occupation
  - relationship
  - race
  - sex
  - country
  
target_column: salary



  


