module_1:
    class: SVC
    module: sklearn.svm
    params:
      c: 1.0
    search_param_grid:
      kernel:
      - 'linear'
      - 'poly'
      - 'sigmoid'
    verbose:
      - true
      - false
  module_2:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      n_neighbors: 5
    search_param_grid:
      n_neighbors:
      - 6
      - 7
      - 9
      - 11
  module_3:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      min_samples_split: 2
    search_param_grid:
      max_depth:
      - 30
      - 50
      - 80
      - 100
  module_4:
    class: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 50
    search_param_grid:
      n_estimators:
      - 30
      - 60
      - 80
  module_5:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 40
    search_param_grid:
      n_estimators:
      - 40
      - 80
      - 100