name: Railway Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Railway
        uses: devtomio/action-railway@v1.1.4
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway deploy --platform python --env FLASK_APP=app.py,FLASK_ENV=production
